using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Systems;
using Content.Shared.Administration;
using Content.Shared.Radium.Nanites;
using Content.Shared.Dataset;
using Content.Shared.Lathe;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Utility;

namespace Content.Client.Radium.Nanites.NanitesConsoles.ChamberController;

[GenerateTypedNameReferences]
public sealed partial class NChamberControllerConsoleWindow : FancyWindow
{
    private readonly IPlayerManager _player;
    private readonly IPrototypeManager _proto;
    private readonly IRobustRandom _random;
    private readonly AccessReaderSystem _accessReader;

    public readonly EntityUid Console;

    private uint _maxLength;
    private bool _isPopulating;
    private bool _access;
    private uint? _selectedKey;

    public NChamberControllerConsoleWindow(EntityUid console,
        uint maxLength,
        IPlayerManager playerManager,
        IPrototypeManager prototypeManager,
        IRobustRandom robustRandom,
        AccessReaderSystem accessReader)
    {
        RobustXamlLoader.Load(this);

        Console = console;
        _player = playerManager;
        _proto = prototypeManager;
        _random = robustRandom;
        _accessReader = accessReader;

        _maxLength = maxLength;

        OpenCentered();
    }

}
